Party: SYRIZA  Votes: 1
Party: EAN  Votes: 1
Party: PLEFSI_ELEFTHERIAS  Votes: 1
Party: ELLHNVN_SYNELEFSIS  Votes: 4
Party: SOCIAL  Votes: 2
Party: NIKH  Votes: 2
Party: KKE  Votes: 2
Party: MERA25  Votes: 1
Party: ELLHNIKH_LYSH  Votes: 1
Party: PASOK  Votes: 1
Total number of votes:16
